const POST_LIST = [
    {post_no: 1, post_writer: 'NAVER GAME', post_date: '2024.12.02', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL 케스파컵 특별 상품 안내 - 경기 티켓', post_detail: `2024 LoL 케스파컵 특별 상품 안내 - 경기 티켓`, post_tag: ''},
    {post_no: 2, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: `2024 LoL KeSPA CUP 로스터`, post_tag: ''},
    {post_no: 3, post_writer: 'NAVER GAME', post_date: '2021.01.25', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: 'LCK 주간 HOT 매치 승부예측 이벤트!', post_detail: `<p>안녕하세요 네이버게임입니다.</p><p>많은 분들이 기다리시던 LCK 2021 스프링 시즌이 3주차에 접어들었습니다!</p><p>벌써 많은 명경기가 쏟아지면서 '황부리그' LCK를 기다리시던 유저들의 기대감을 잘 채워주고 있다고 생각하는데요</p>`, post_tag: ''},
    {post_no: 4, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 5, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 6, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 7, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 8, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 9, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 10, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 11, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 12, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 13, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 14, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 15, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 16, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 17, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 18, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 19, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 20, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 21, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 22, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 23, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 24, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 25, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 26, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
    {post_no: 27, post_writer: 'NAVER GAME', post_date: '2024.11.29', post_views: 0, post_buff: 0, post_nuff: 0, post_tab: '공지', post_title: '2024 LoL KeSPA CUP 로스터', post_detail: ``, post_tag: ''},
]